import { useEffect, useState } from "react";
import Footer from "../../components/global_components/footer/Footer";
import Navbar from "../../components/global_components/navbar/Navbar";
import NavbarMobile from "../../components/global_components/navbar/NavbarMobile";

const Politicas=()=>{
    const [isMobile, setIsMobile] = useState(window.innerWidth < 768); // Definir 768 como el punto de corte para móvil

    useEffect(() => {
        const handleResize = () => {
        setIsMobile(window.innerWidth < 768);
        };

        window.addEventListener('resize', handleResize);

        return () => {
        window.removeEventListener('resize', handleResize);
        };
    }, []);

    const politicas=`<div>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 14px; font-family: Calibri, sans-serif;"><strong>Pol&iacute;ticas de Privacidad</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Fecha &uacute;ltima actualizaci&oacute;n: 07 de Julio de 2023</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">De conformidad con la Ley Org&aacute;nica de Protecci&oacute;n de Datos Personales del Gobierno Nacional del Ecuador, publicada en el Registro Oficial el 22 de mayo de 2021, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de estos datos, ARACNO C&Iacute;A.&nbsp;LTDA. informa a los usuarios de la aplicaci&oacute;n VISITAECUADOR.COM (en adelante, la Aplicaci&oacute;n), acerca del tratamiento de los datos personales, que ellos voluntariamente hayan facilitado durante el proceso de registro, acceso y utilizaci&oacute;n del servicio.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>1. IDENTIFICACI&Oacute;N DEL RESPONSABLE DEL TRATAMIENTO.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">ARACNO C&Iacute;A. LTDA.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Calle del Bat&aacute;n 5-137 y Esmeraldas. Cuenca (Ecuador)</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">R.U.C.: 0190167895001</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Edificio Visita Ecuador Disney Concierge</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Correo electr&oacute;nico de contacto: <a href="mailto:contacto@visitaecuador.com">contacto@visitaecuador.com</a>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Es la entidad responsable del tratamiento de los datos facilitados por los clientes de la Aplicaci&oacute;n (en adelante, el/los Usuario/s).&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>2. FINALIDAD DEL TRATAMIENTO DE DATOS.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Para proceder al registro, acceso y posterior uso de la Aplicaci&oacute;n, el Usuario deber&aacute; facilitar -de forma voluntaria-, datos de car&aacute;cter personal (esencialmente, identificativos y de contacto), los cuales ser&aacute;n incorporados a soportes automatizados titularidad de ARACNO C&Iacute;A. LTDA.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">La recogida, almacenamiento, modificaci&oacute;n, estructuraci&oacute;n y en su caso, eliminaci&oacute;n, de los datos proporcionados por los Usuarios, constituir&aacute;n operaciones de tratamiento llevadas a cabo por el Responsable, con la finalidad de garantizar el correcto funcionamiento de la Aplicaci&oacute;n, mantener la relaci&oacute;n de prestaci&oacute;n de servicios y/o comercial con el Usuario, y para la gesti&oacute;n, administraci&oacute;n, informaci&oacute;n, prestaci&oacute;n y mejora del servicio.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Los datos personales facilitados por el Usuario -especialmente, el correo electr&oacute;nico o e-mail- podr&aacute;n emplearse tambi&eacute;n para remitir boletines (newsletters), as&iacute; como comunicaciones comerciales de promociones y/o publicidad de la Aplicaci&oacute;n, siempre y cuando, el Usuario haya prestado previamente su consentimiento expreso para la recepci&oacute;n de estas comunicaciones al haber aceptado los t&eacute;rminos y condiciones de uso de la Aplicaci&oacute;n y haberse registrado en la misma.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>3. MEDIOS DE RECOPILACI&Oacute;N DE DATOS.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Cuando se visita el sitio web <a href="http://www.visitaecuador.com">www.visitaecuador.com</a> o se usa la aplicaci&oacute;n m&oacute;vil, de manera autom&aacute;tica, recopilamos cierta informaci&oacute;n del ordenador, Tablet o tel&eacute;fono m&oacute;vil por el cual se accede, como es el caso de: direcci&oacute;n IP, software de exploraci&oacute;n de internet, actividad en l&iacute;nea como viajes visualizados y reservaciones realizadas. El motivo por el cual se recopila esta informaci&oacute;n de manera autom&aacute;tica es para poder prestar un mejor servicio y una mejor experiencia al USUARIO y as&iacute; poder evitar fraudes.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">En caso de registrarse en VISITAECUADOR.COM a trav&eacute;s de una cuenta de redes sociales, se podr&aacute; recibir informaci&oacute;n del Usuario a trav&eacute;s de ese proveedor de red social de conformidad con su pol&iacute;tica interna. Esta informaci&oacute;n puede incluir nombre, direcci&oacute;n de correo electr&oacute;nico, foro del perfil, g&eacute;nero, lista de amigos y dem&aacute;s informaci&oacute;n que se autorice a ser recibida.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">VISITAECUADOR.COM no recopila ning&uacute;n tipo de informaci&oacute;n referente a tarjetas de cr&eacute;dito o medios de pago de los Usuarios.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>Utilizaci&oacute;n de la informaci&oacute;n general:&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">El resto de informaci&oacute;n proporcionada por el Usuario se utiliza para prop&oacute;sitos generales como: proporcionar informaci&oacute;n sobre los servicios que el Usuario solicita mediante contacto telef&oacute;nico con nuestra Central de Reservas; proporcionar confirmaciones y/o actualizaciones con respecto a reserva de hoteles; para administrar la cuenta del Usuario; para que VISITAECUADOR.COM pueda comunicarse con el Usuario; para poder solucionar toda consulta, pedido o reclamo realizada por el Usuario en tiempo real; para realizar notificaciones PUSH; para notificar sobre eventos, actividades, promociones y/o concursos que pudiesen ser de inter&eacute;s del Usuario; para solicitar informaci&oacute;n por medio de encuestas; para prevenir actividades ilegales o prohibidas, y para hacer efectivos nuestros t&eacute;rminos y condiciones de uso.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>Uso de Cookies:&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">VISITAECUADOR.COM usa cookies para almacenar la informaci&oacute;n o contenido en raz&oacute;n de los Usuarios y las visitas respectivas a la p&aacute;gina web <a href="http://www.visitaecuador.com">www.visitaecuador.com</a> y su aplicaci&oacute;n m&oacute;vil.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>Links:&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">La p&aacute;gina web <a href="http://www.visitaecuador.com">www.visitaecuador.com</a> y la aplicaci&oacute;n m&oacute;vil, podr&aacute;&nbsp;contener links a p&aacute;ginas de terceros, ante lo cual VISITAECUADOR.COM no asume ninguna responsabilidad por las pol&iacute;ticas de privacidad de estos sitios web.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>4. LEGITIMACI&Oacute;N.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">El tratamiento de los datos del Usuario, se realiza con las siguientes bases jur&iacute;dicas que legitiman el mismo:&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <ul>
        <li style='margin-top: 0cm; margin-right: 0cm; margin-bottom: 0cm; font-size: 16px; font-family: "Times New Roman", serif; border: none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">La solicitud de informaci&oacute;n y/o el registro para acceder a los servicios de la Aplicaci&oacute;n, cuyos t&eacute;rminos y condiciones se pondr&aacute;n a disposici&oacute;n del Usuario en todo caso, con car&aacute;cter previo, para su expresa aceptaci&oacute;n.&nbsp;</span></li>
        <li style='margin-top: 0cm; margin-right: 0cm; margin-bottom: 0cm; font-size: 16px; font-family: "Times New Roman", serif; border: none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">El consentimiento libre, espec&iacute;fico, informado e inequ&iacute;voco del Usuario, poniendo a su disposici&oacute;n la presente pol&iacute;tica de privacidad, que deber&aacute; aceptar mediante una declaraci&oacute;n o una clara acci&oacute;n afirmativa, como el marcado de una casilla dispuesta para tal efecto.&nbsp;<br>&nbsp;</span></li>
    </ul>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">En caso de que el Usuario no facilite a ARACNO C&Iacute;A.&nbsp;LTDA. sus datos, o lo haga de forma err&oacute;nea o incompleta, no ser&aacute; posible proceder al uso de la Aplicaci&oacute;n.&nbsp;<br>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>5. CONSERVACI&Oacute;N DE LOS DATOS PERSONALES.&nbsp;<br></strong>&nbsp;Los datos personales proporcionados por el Usuario, se conservar&aacute;n en los sistemas y bases de datos del Responsable del Tratamiento, mientras aqu&eacute;l contin&uacute;e haciendo uso de la Aplicaci&oacute;n, y siempre que no solicite su supresi&oacute;n.&nbsp;<br>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Con el objetivo de depurar las posibles responsabilidades derivadas del tratamiento, los datos se conservar&aacute;n por un per&iacute;odo m&iacute;nimo de cinco a&ntilde;os.&nbsp;<br>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>6. DESTINATARIOS.&nbsp;<br></strong>&nbsp;Los datos recolectados por la Aplicaci&oacute;n M&oacute;vil se comunicar&aacute;n exclusivamente a las empresas del Grupo ARACNO C&Iacute;A.&nbsp;LTDA. Fuera de esto, no se comunicar&aacute; o facilitar&aacute; dicha informaci&oacute;n a ninguna otra entidad, salvo obligaci&oacute;n legal o en cualquier caso, previa solicitud del consentimiento del Usuario.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><br>&nbsp;De otra parte, ARACNO C&Iacute;A.&nbsp;LTDA. podr&aacute; dar acceso o transmitir los datos personales facilitados por el Usuario, a terceros proveedores de servicios, con los que haya suscrito acuerdos de encargo de tratamiento de datos, y que &uacute;nicamente accedan a dicha informaci&oacute;n para prestar un servicio en favor y por cuenta del Responsable.&nbsp;<br>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>7. PROTECCI&Oacute;N DE LA INFORMACI&Oacute;N ALOJADA.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">El Responsable del Tratamiento, adopta las medidas necesarias para garantizar la seguridad, integridad y confidencialidad de los datos conforme a lo dispuesto en la Ley Org&aacute;nica de Protecci&oacute;n de Datos Personales del Gobierno Nacional del Ecuador, publicada en el Registro Oficial el 22 de mayo de 2021, relativo a la protecci&oacute;n de las personas f&iacute;sicas en lo que respecta al tratamiento de datos personales y a la libre circulaci&oacute;n de los mismos.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Si bien el Responsable, realiza copias de seguridad de los contenidos alojados en sus servidores, sin embargo no se responsabiliza de la p&eacute;rdida o el borrado accidental de los datos por parte de los Usuarios. De igual manera, no garantiza la reposici&oacute;n total de los datos borrados por los Usuarios, ya que los citados datos podr&iacute;an haber sido suprimidos y/o modificados durante el periodo de tiempo transcurrido desde la &uacute;ltima copia de seguridad.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Los servicios facilitados o prestados a trav&eacute;s de la Aplicaci&oacute;n, excepto los servicios espec&iacute;ficos de backup, no incluyen la reposici&oacute;n de los contenidos conservados en las copias de seguridad realizadas por el Responsable del Tratamiento, cuando esta p&eacute;rdida sea imputable al usuario; en este caso, se determinar&aacute; una tarifa acorde a la complejidad y volumen de la recuperaci&oacute;n, siempre previa aceptaci&oacute;n del usuario.&nbsp;La reposici&oacute;n de datos borrados s&oacute;lo est&aacute; incluida en el precio del servicio cuando la p&eacute;rdida del contenido sea debida a causas atribuibles al Responsable.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Los usuarios que hayan creado una cuenta a trav&eacute;s de la p&aacute;gina web&nbsp;<a href="http://www.visitaecuador.com">www.visitaecuador.com</a> o por medio de la aplicaci&oacute;n m&oacute;vil de VISITAECUADOR.COM se encuentran protegidos por contrase&ntilde;a o password respectivo. Se tomar&aacute;n todas las precauciones para mantener la seguridad de la cuenta del usuario y la informaci&oacute;n contenida en esta ser&aacute; mantenida en privado.</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>8. EJERCICIO DE DERECHOS.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">ARACNO C&Iacute;A. LTDA. informa al Usuario que le asisten los derechos de acceso, rectificaci&oacute;n, limitaci&oacute;n, supresi&oacute;n, oposici&oacute;n y portabilidad, los cuales podr&aacute; ejercitar mediante petici&oacute;n dirigida al correo electr&oacute;nico <a href="mailto:contacto@visitaecuador.com">contacto@visitaecuador.com</a>&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">Asimismo, el Usuario tiene derecho a revocar el consentimiento inicialmente prestado, y a interponer reclamaciones de derechos frente al Ministerio de Telecomunicaciones del Ecuador (MINTEL).&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;"><strong>9. COMUNICACIONES COMERCIALES POR V&Iacute;A ELECTR&Oacute;NICA.&nbsp;</strong></span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">En aplicaci&oacute;n de la LOPDP (Ley Org&aacute;nica de Protecci&oacute;n de Datos Personales), ARACNO C&Iacute;A. LTDA. no enviar&aacute; comunicaciones publicitarias o promocionales por correo electr&oacute;nico u otro medio de comunicaci&oacute;n electr&oacute;nica equivalente que previamente no hubieran sido solicitadas o expresamente autorizadas por los destinatarios de las mismas.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">En el caso de usuarios con los que exista una relaci&oacute;n contractual, jur&iacute;dica o de servicios previa, el Responsable del Tratamiento, s&iacute; est&aacute; autorizado al env&iacute;o de comunicaciones comerciales referentes a productos o servicios del Responsable que sean similares a los que inicialmente fueron objeto de contrataci&oacute;n con el cliente.&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px; font-family: Calibri, sans-serif;">&nbsp;</span></p>
    <p style='margin:0cm;font-size:16px;font-family:"Times New Roman",serif;border:none;'><span style="font-size: 12px;"><span style="font-family: Calibri, sans-serif;">En caso de que el Usuario quiera darse de baja a la hora de recibir las citadas comunicaciones, &nbsp;o requiera contactarse por quejas, reclamos o sugerencias, podr&aacute; hacerlo remitiendo su voluntad por e-mail al correo electr&oacute;nico </span><a href="mailto:contacto@visitaecuador.com"><span style="font-family: Calibri, sans-serif;">contacto@visitaecuador.com</span></a> </span></p>
  </div>`;
    return(
        <div>
            {
                isMobile
                ?<NavbarMobile/>
                :<Navbar/>
            }
            <div className="flex flex-col mx-auto my-28 max-w-6xl py-6 sm:flex-row sm:px-6 lg:px-8 items-center">
            <div dangerouslySetInnerHTML={{ __html: politicas }} />
            </div>
            <Footer></Footer>
        </div>
    );
}
export default Politicas;