class Producto{
    constructor(
        Titulo, 
        TipoTiempo, 
        PrecioProducto, 
        AniosVendidos, 
        Anios, 
        Recurrencia, 
        IdTablaListaPrecio, 
        IdTablaServicioWeb, 
        NombreComercial, 
        IdTipoDiferido,
        NombreTipoDiferido,
        IdProducto,
        IdProductoSuscripcion,
        IdListaPrecioProducto,
        TiempoVendido,
        Tiempo
    ){
        this.Titulo=Titulo;
        this.TipoTiempo=TipoTiempo;
        this.PrecioProducto=PrecioProducto;
        this.AniosVendidos=AniosVendidos;
        this.Anios=Anios;
        this.Recurrencia=Recurrencia;
        this.IdTablaListaPrecio=IdTablaListaPrecio; 
        this.IdTablaServicioWeb=IdTablaServicioWeb; 
        this.NombreComercial=NombreComercial;
        this.IdTipoDiferido=IdTipoDiferido;
        this.NombreTipoDiferido=NombreTipoDiferido;
        this.IdProducto=IdProducto;
        this.IdProductoSuscripcion=IdProductoSuscripcion;
        this.IdListaPrecioProducto=IdListaPrecioProducto;
        this.TiempoVendido=TiempoVendido;
        this.Tiempo=Tiempo;
    }
}

export default Producto